= API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[category-api]]
== 카테고리 API

[[category-get-all]]
=== 전체 카테고리 조회

`GET /api-v1/categories`

operation::category-get-all[snippets='http-request,http-response,response-fields']

[[roadmap-api]]
== 로드맵 API

[[roadmap-create]]
=== 로드맵 생성

`POST /api-v1/roadmap`

operation::roadmap-create[snippets='request-fields,http-request,http-response,response-fields']

[[roadmap-clone]]
=== 로드맵 복제

`POST /api-v1/roadmap/{id}/clone`

operation::roadmap-clone[snippets='path-parameters,request-fields,http-request,http-response,response-fields']

[[roadmap-get-by-id]]
=== ID로 로드맵 조회

`GET /api-v1/roadmap/{id}`

operation::roadmap-get-by-id[snippets='path-parameters,http-request,http-response,response-fields']

[[star-roadmap-api]]
== 별점 로드맵 API

[[star-roadmap-create]]
=== 별점 생성

`POST /api-v1/star-roadmaps`

operation::star-roadmap-create[snippets='request-fields,http-request,http-response']

[[star-roadmap-get-by-id]]
=== ID로 별점 조회

`GET /api-v1/star-roadmaps/{id}`

operation::star-roadmap-get-by-id[snippets='path-parameters,http-request,http-response,response-fields']

[[star-roadmap-get-by-user-id]]
=== 사용자 ID로 별점 목록 조회

`GET /api-v1/star-roadmaps?userId={userId}`

operation::star-roadmap-get-by-user-id[snippets='query-parameters,http-request,http-response,response-fields']

[[star-roadmap-get-by-roadmap-id]]
=== 로드맵 ID로 별점 목록 조회

`GET /api-v1/star-roadmaps?roadmapId={roadmapId}`

operation::star-roadmap-get-by-roadmap-id[snippets='query-parameters,http-request,http-response,response-fields']

[[star-roadmap-update]]
=== 별점 수정

`PUT /api-v1/star-roadmaps/{id}`

operation::star-roadmap-update[snippets='path-parameters,request-fields,http-request,http-response']

[[star-roadmap-delete]]
=== 별점 삭제

`DELETE /api-v1/star-roadmaps`

operation::star-roadmap-delete[snippets='request-fields,http-request,http-response']

[[travel-api]]
== 여행 API

[[travel-create]]
=== 여행 생성

`POST /api-v1/travels`

operation::travel-create[snippets='request-fields,http-request,http-response,response-fields']

[[travel-get-by-id]]
=== 여행 단건 조회

`GET /api-v1/travels/{id}`

operation::travel-get-by-id[snippets='path-parameters,http-request,http-response,response-fields']

[[travel-update]]
=== 여행 업데이트

`PUT /api-v1/travels`

operation::travel-update[snippets='request-fields,http-request,http-response,response-fields']

[[travel-get-by-user-id]]
=== 유저 ID로 여행 목록 조회

`GET /api-v1/travels/user/{userId}`

operation::travel-get-by-user-id[snippets='path-parameters,http-request,http-response,response-fields']

